apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-green
data:
  index.html: |
      Nginx V1.15.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx_green
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: index-html
      volumes:
      - name: index-html
        configMap:
          name: index-html-green
          items:
            - key: index.html
              path: index.html
