apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodename
          operator: In
          values:
          - node1
